server.port=8085

# =============================
# USER SERVICE ROUTE
# =============================
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

# =============================
# PRODUCT SERVICE ROUTE
# =============================
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/products/**

# =============================
# CART SERVICE ROUTE
# =============================
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/cart/**


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery locator (optional)
spring.cloud.gateway.mvc.discovery.locator.enabled=true
spring.cloud.gateway.mvc.discovery.locator.lower-case-service-id=true

# ========= USER SERVICE =========
spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/users/**

# ========= PRODUCT SERVICE =========
spring.cloud.gateway.mvc.routes[1].id=product-service
spring.cloud.gateway.mvc.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/products/**

# ========= CART SERVICE =========
spring.cloud.gateway.mvc.routes[2].id=cart-service
spring.cloud.gateway.mvc.routes[2].uri=lb://CART-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/cart/**
