# Notification Service Properties

spring.application.name=notification-service

server.port=8087

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =========================================================
# Kafka Consumer Configuration
# =========================================================

spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.properties.isolation.level=read_committed

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.shoppingkart.*

# Kafka Producer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =========================================================
# Consumer
# =========================================================

spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell JsonDeserializer exactly which class to create
spring.kafka.consumer.properties.spring.json.value.default.type=com.shoppingkart.notificationservice.event.OrderCreatedEvent

# We intentionally don't depend on producer Java type headers
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Required because the event contains nested objects
spring.kafka.consumer.properties.spring.json.trusted.packages=com.shoppingkart.notificationservice.event
